doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
            _int4: string
            name: string
            regtype: string

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            AuthBundle:
                is_bundle: false
#                type: annotation
                dir: "%kernel.project_dir%/src/AuthBundle/Entity"
                prefix: 'App\AuthBundle\Entity'
                alias: AuthBundle
