#!/bin/bash
FILE=/opt/.env.local
if [ -f "$FILE" ]; then
    source $FILE
fi

echo "Xdebug settings will be applied is: $XDEBUG_ENABLED_IN_CONTAINER"
if [ "$XDEBUG_ENABLED_IN_CONTAINER" == "dev" ] || [ "$XDEBUG_ENABLED_IN_CONTAINER" == "ci" ]; then
    pecl install xdebug-3.0.4
    docker-php-ext-enable xdebug
    echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini
fi

if [[ "$XDEBUG_ENABLED_IN_CONTAINER" == "ci" ]]; then
    echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/xdebug.ini
elif [[ "$XDEBUG_ENABLED_IN_CONTAINER" == "dev" ]]; then
    echo "xdebug.mode=develop,debug,coverage" >> /usr/local/etc/php/conf.d/xdebug.ini
fi

exit 0
